development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  port: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PORT"] %>
  database: donde_cooperamos
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PASSWORD"] %>

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  port: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PORT"] %>
  database: donde_cooperamos
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PASSWORD"] %>

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  port: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PORT"] %>
  database: donde_cooperamos
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PASSWORD"] %>

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  port: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PORT"] %>
  database: donde_cooperamos
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PASSWORD"] %>
