development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  port: <%= ENV["OPENSHIFT_POSTGRESQL_DB_PORT"] %>
  database: iom_development
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_test
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password:

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_staging
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_development
  username: <%= ENV["OPENSHIFT_POSTGRESQL_DB_USERNAME"] %>
  password:
