development:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  host:
  database: iom_development
  username:
  password:

test:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_test
  username:
  password:

staging:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production
  username:
  password:

production:
  adapter: postgresql
  template: template_postgis
  encoding: unicode
  database: iom_production
  username:
  password:
